### PR TITLE
Fix(Deploy): fix SQL error when deploy target option used is 'No restriction' defined with `-1`

### LINKED ISSUE #817: Self-Service package install feature is broken
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### GLPI Version

11.0.2

### Plugin version

1.6.2

### Bug description

Unable to set a a deployment target for a profile.

If I create a self service deployment package and try to set target:
Type: Profil -> Self-Service
Entity: Unrestricted

It show an error

Even when trying any combination of target I can't get any package to show in the self service tab.

Image

### Relevant log output

```shell
[2025-11-20 11:09:51] glpi.CRITICAL:   *** Uncaught PHP Exception RuntimeException: "MySQL query error: Out of range value for column 'entities_id' at row 1 (1264) in SQL query "INSERT INTO `glpi_plugin_glpiinventory_deploypackages_profiles` (`plugin_glpiinventory_deploypackages_id`, `profiles_id`, `entities_id`, `is_recursive`) VALUES ('13', '1', '-1', '0')"." at DBmysql.php line 371
  Backtrace :
  .\src\DBmysql.php:371                              
  .\src\DBmysql.php:1327                             DBmysql->doQuery()
  .\src\CommonDBTM.php:776                           DBmysql->insert()
  .\src\CommonDBTM.php:1381                          CommonDBTM->addToDB()
  ...\glpiinventory\front\deploypackage.form.php:100 CommonDBTM->add()
  ...Glpi\Controller\LegacyFileLoadController.php:64 require()
  .\vendor\symfony\http-kernel\HttpKernel.php:181    Glpi\Controller\LegacyFileLoadController->__invoke()
  .\vendor\symfony\http-kernel\HttpKernel.php:76     Symfony\Component\HttpKernel\HttpKernel->handleRaw()
  .\vendor\symfony\http-kernel\Kernel.php:197        Symfony\Component\HttpKernel\HttpKernel->handle()
  .\public\index.php:70                              Symfony\Component\HttpKernel\Kernel->handle()
```

### Page URL

_No response_

### Steps To reproduce

1. Create a deployment package
2. Try to assign the target as mentioned above
3. Try to access any package in the self service page, none is available

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by stonebuzz**
…riction' defined with

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [ ] I have performed a self-review of my code.
- [ ] I have added tests (when available) that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes #817

Fix SQL error when the 'No Restriction' option (defined as `-1`) is used for the deployment target.

This option has been removed, as it is equivalent to selecting 'Root + Recursive'

### CODE REVIEW

File: ajax/visibility.php [hunk 1]
```diff
@@ -0,0 +1,134 @@
...
+    if (isset($_POST['prefix']) && !empty($_POST['prefix'])) {
+        $prefix = $_POST['prefix'] . '[';
+        $suffix = ']';
+    } else {
+        $_POST['prefix'] = '';
+    }
+
+    echo "<div class='d-flex'>";
+    switch ($_POST['type']) {
+        case 'User':
```
Comment (trasher) [inline ajax/visibility.php]:
```suggestion
        case User::class:
```

File: ajax/visibility.php [hunk 2]
```diff
@@ -0,0 +1,134 @@
...
+            $params = [
+                'right' => isset($_POST['allusers']) ? 'all' : $_POST['right'],
+                'name' => $prefix . 'users_id' . $suffix,
+            ];
+            User::dropdown($params);
+            $display = true;
+            break;
+
+        case 'Group':
```
Comment (trasher) [inline ajax/visibility.php]:
```suggestion
        case Group::class:
```

File: ajax/visibility.php [hunk 3]
```diff
@@ -0,0 +1,134 @@
...
+                    'prefix'   => $_POST['prefix'],
+                ],
+            ];
+
+            Group::dropdown($params);
+            echo "<span id='subvisibility$rand'></span>";
+            $display = true;
+            break;
+
+        case 'Entity':
```
Comment (trasher) [inline ajax/visibility.php]:
```suggestion
        case Entity::class:
```
