### PR TITLE
Fix phpstan issues on remaining directories

### LINKED ISSUE #713: Some path are missing in phpstan config
I think some are missing:
```suggestion
    paths:
        - ajax
        - front
        - inc
        - install
        - public
        - report
        - tests
        - hook.php
        - rector.php
        - setup.php
    excludePaths:
        - tests/files
```

_Originally posted by @Rom1-B in https://github.com/glpi-project/glpi-inventory-plugin/pull/654#discussion_r2216044766_

### PR DESCRIPTION
**Pull request by trasher**
close #713

### CODE REVIEW

File: install/update.php [hunk 1]
```diff
@@ -3933,29 +3943,6 @@ function do_networkport_migration($migration)
     );
     $migration->migrationOneTable($newTable);
 
-    // Update with mapping
```
Comment (trasher) [inline install/update.php:3936]: Alternative is to put back the `PluginGlpiinventoryMapping` class... Seems like this is useful only for very old versions of the plugin.

Comment (stonebuzz) [reply install/update.php:3936]: It no longer exists on the 10bufxies branch; I can only find it on the glpi9.5 branch. In my opinion, it hasn’t been used for quite some time.
