### PR TITLE
Fix queries expected to be an array, not a string

### LINKED ISSUE #468: Target a task ( My iprange) : Uncaught Exception TypeError: Dropdown::addNewCondition()
### Describe the bug

When i want to select my iprange and i want target my tasks to target task. I have error log

1 go to here
image

2 select
image

3 target task, Enjoy and log error
image

4 my task
image

```shell
[2024-02-09 15:22:36] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Dropdown::addNewCondition(): Argument #1 ($condition) must be of type array, string given, called in /var/www/html/glpi/src/Dropdown.php on line 212 in /var/www/html/glpi/src/Dropdown.php at line 454
  Backtrace :
  src/Dropdown.php:212                               Dropdown::addNewCondition()
  ...lace/glpiinventory/ajax/dropdown_taskjob.php:46 Dropdown::show()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "taskjobs_id" in /var/www/html/glpi/marketplace/glpiinventory/inc/task.class.php at line 1931
  Backtrace :
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "targets" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 848
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 860
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "taskjobs_id" in /var/www/html/glpi/marketplace/glpiinventory/inc/task.class.php at line 1931
  Backtrace :
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "targets" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 848
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 860
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "taskjobs_id" in /var/www/html/glpi/marketplace/glpiinventory/inc/task.class.php at line 1931
  Backtrace :
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "targets" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 848
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 860
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "taskjobs_id" in /var/www/html/glpi/marketplace/glpiinventory/inc/task.class.php at line 1931
  Backtrace :
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "targets" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 848
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 860
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "taskjobs_id" in /var/www/html/glpi/marketplace/glpiinventory/inc/task.class.php at line 1931
  Backtrace :
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "targets" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 848
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 860
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "taskjobs_id" in /var/www/html/glpi/marketplace/glpiinventory/inc/task.class.php at line 1931
  Backtrace :
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "targets" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 848
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 860
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "taskjobs_id" in /var/www/html/glpi/marketplace/glpiinventory/inc/task.class.php at line 1931
  Backtrace :
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "targets" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 848
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 860
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "taskjobs_id" in /var/www/html/glpi/marketplace/glpiinventory/inc/task.class.php at line 1931
  Backtrace :
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "targets" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 848
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 860
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "taskjobs_id" in /var/www/html/glpi/marketplace/glpiinventory/inc/task.class.php at line 1931
  Backtrace :
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "targets" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 848
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 860
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "taskjobs_id" in /var/www/html/glpi/marketplace/glpiinventory/inc/task.class.php at line 1931
  Backtrace :
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "targets" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 848
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 860
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "taskjobs_id" in /var/www/html/glpi/marketplace/glpiinventory/inc/task.class.php at line 1931
  Backtrace :
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "targets" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 848
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:22:37] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/marketplace/glpiinventory/inc/taskjob.class.php at line 860
  Backtrace :
  marketplace/glpiinventory/inc/task.class.php:1931  PluginGlpiinventoryTaskjob->additemtodefatc()
  src/MassiveAction.php:1420                         PluginGlpiinventoryTask::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1398                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
  public/index.php:82                                require()
  
[2024-02-09 15:27:06] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Dropdown::addNewCondition(): Argument #1 ($condition) must be of type array, string given, called in /var/www/html/glpi/src/Dropdown.php on line 212 in /var/www/html/glpi/src/Dropdown.php at line 454
  Backtrace :
  src/Dropdown.php:212                               Dropdown::addNewCondition()
  ...lace/glpiinventory/ajax/dropdown_taskjob.php:46 Dropdown::show()
  public/index.php:82                                require()
```

### To reproduce

1 . go to : /glpi/marketplace/glpiinventory/front/iprange
2 . Select Iprange
3 . Modify and Target a task
4 . Select Job

### Expected behavior

1 . go to : /glpi/marketplace/glpiinventory/front/iprange
2 . Select Iprange
3 . Modify and Target a task
4 . Select Job

### Operating system

Linux

### GLPI Agent version

1.6.1

### GLPI version

10.0.11

### GLPIInventory plugin

1.3.4

### Additional context

GLPI 10.0.12

### PR DESCRIPTION
**Pull request by trasher**
closes #468

### CODE REVIEW

File: ajax/dropdownjobdefinition.php [hunk 1]
```diff
@@ -90,10 +90,10 @@
             break;
 
         case "group":
-            $cond = ($actortype == 'assign' ? $cond = '`is_assign`' : $cond = '`is_requester`');
+            $cond = ($actortype == 'assign' ? $cond = 'is_assign' : $cond = 'is_requester');
```
Comment (cedric-anne) [inline ajax/dropdownjobdefinition.php:93]:
```suggestion
            $cond = $actortype == 'assign' ? 'is_assign' : 'is_requester';
```

**Review by cedric-anne — APPROVED** [review]
